### ISSUE TITLE
Consider dispatch semantics

### ISSUE THREAD

**Issue by vinipsmaker** [blinktrade/iofiber#6]
For now only post semantics (a.k.a. run-to-completion) are supported.

Gotta be very careful with:

* Which functions are candidates for dispatch semantics? Functions that may suspend are good candidates.
* Deadlocks.
* Throwing a `fiber_interruption` exception to the wrong fiber because jumping handles when dispatch semantics are on.

**Comment by vinipsmaker2** [comment]
As of <https://github.com/blinktrade/iofiber/commit/20371b97282ac50670ada498fa263b86b08199c6>, I have tuned all executors actions.

Now there is the problem: shall the API allow the user to ask for dispatch semantics (e.g. on fiber spawning)? I don't see how this fits anywhere else besides the `spawn()` function. Therefore, it's so little value for such complicated logic that I won't consider implementing it.
